# Generated by Django 6.1.1 on 2026-09-03 19:10

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
